# Generated by Django 3.0.3 on 2020-03-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tranings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='weekDay',
            field=models.SmallIntegerField(default=0, verbose_name='День недели'),
        ),
    ]
